// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5NeO0bwuMevE9z-cyNiRhumwlAJuUAc',
    appId: '1:921584366710:web:47c54ef4a34df7a3a79b57',
    messagingSenderId: '921584366710',
    projectId: 'payflow-a95bf',
    authDomain: 'payflow-a95bf.firebaseapp.com',
    storageBucket: 'payflow-a95bf.appspot.com',
    measurementId: 'G-XVJQQD0CM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABKsugm46s8eccPKxqNfcwexcxQrAVYaU',
    appId: '1:921584366710:android:400f3598d6ec7782a79b57',
    messagingSenderId: '921584366710',
    projectId: 'payflow-a95bf',
    storageBucket: 'payflow-a95bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOvGVb9mfnY7RsKNTCvPFzA2fvoAJngC0',
    appId: '1:921584366710:ios:cb638898ab601d87a79b57',
    messagingSenderId: '921584366710',
    projectId: 'payflow-a95bf',
    storageBucket: 'payflow-a95bf.appspot.com',
    androidClientId: '921584366710-ela82np71r5jgneehl3e3bnlb9dvlpb7.apps.googleusercontent.com',
    iosClientId: '921584366710-r1ogc6a9c6dg3hhleif36g5irg6195mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );
}
